on:
  push:
  pull_request:
  merge_group:

name: CI
jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        allow-failure:
        - false
        include:
        - python-version: '3.13-dev'
          allow-failure: true
    continue-on-error: ${{ matrix.allow-failure }}
    name: 'test (${{ matrix.python-version }})'
    steps:
    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install codecov build
        pdm install --dev
    - name: Run tests
      run: |
        pdm run test
    - name: Submit code coverage
      run: |
        codecov

  # smoketest: # If we plug this into downstream projects, does magic smoke escape?
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       project:
  #         - MazinLab/MKIDPipeline
  #   name: 'smoke (${{ matrix.project }})'
  #   steps:
  #   - name: Check out MKIDCore source code
  #     uses: actions/checkout@v4
  #     with:
  #       path: MKIDCore
  #       fetch-depth: 0
  #   - name: Check out source code
  #     uses: actions/checkout@v4
  #     with:
  #       repository: ${{ matrix.project }}
  #       path: project
  #       fetch-depth: 0
  #   - name: Set up PDM
  #     uses: pdm-project/setup-pdm@v4
  #   - name: Install dependencies
  #     working-directory: project
  #     run: |
  #       pdm install --dev
  #   - name: Use MKIDCore HEAD revision
  #     working-directory: project
  #     run: |
  #       pdm add ../MKIDCore
  #   - name: Run tests
  #     working-directory: project
  #     run: |
  #       pdm run test

  required: # group all required workflows into one to avoid reconfiguring this in Actions settings
    needs:
      - test
    if: ${{ always() && !contains(needs.*.result, 'cancelled') }}
    runs-on: ubuntu-latest
    steps:
      - run: ${{ contains(needs.*.result, 'failure') && 'false' || 'true' }}
